name: Setup runner
description: Prepare a runner for the tests (install uv, python, project dependencies, etc.)
inputs:
  python-version:
    description: The Python version to use
    required: false
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true
        version: 0.7.6

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-groups
        uv pip install ollama faiss-cpu
        # always test against the latest version of the client
        # TODO: this is not necessarily a good idea. we need to test against both published and latest
        # to find out backwards compatibility issues.
        uv pip install git+https://github.com/meta-llama/llama-stack-client-python.git@main
        uv pip install -e .
