blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://ogx-ai.github.io/docs
    about: Much help can be found in the docs
  - name: Chat on Slack
    url: https://join.slack.com/t/ogx-ai/shared_invite/zt-3uyw5bxj9-tSEwsNZncgkGEKbd4dXIpw
    about: Maybe chatting with the community can help
