blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://ogx-ai.github.io/docs
    about: Much help can be found in the docs
  - name: Join the Discord community
    url: https://discord.gg/bUYRqEvK6
    about: Ask questions and chat with the community
