blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://llamastack.github.io/docs
    about: Much help can be found in the docs
  - name: Chat on Discord
    url: https://discord.gg/llama-stack
    about: Maybe chatting with the community can help
